# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e996952d4c196854d682105bde1444d65aa2f1352f5798f7fc4ab812e9d33dd242319cc760aa739330fd6ead4e766ba17031cd15d1f480908994b31116483d8

test:
  secret_key_base: 3f59e6248f3ef8156f97ba7e3ffd429b235d69d3ad2fc7f54d7b9b0039623182d5f6c3da35779c89ebfb646a65618c77800b0b140193e8de5a451dc50b36726d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
